#!/bin/bash

#Get DJANGOPROJECT* from config file
source config

export PYTHONPATH=$PYTHONPATH:$DJANGOPROJECT_PARENT_PATH:$DJANGOPROJECT_PARENT_PATH/$DJANGOPROJECT
export DJANGO_SETTINGS_MODULE=$DJANGOPROJECT.settings
python Snapshot.py $@ &
